import type { WorkerSnapshot } from "@/types/app";

export const defaultSnapshot: WorkerSnapshot = {
  health: "offline",
  pollingPaused: false,
  queueCount: 0,
  lastSyncAt: null,
  activeJobId: null,
  currentActivity: "Starting worker",
  settings: {
    backendUrl: "https://px.photozone.co.uk",
    machineId: "machine-demo-001",
    machineName: "PX Receiver 01",
    apiToken: "",
    shipstationApiKey: "",
    slackWebhookUrl: "",
    machineAuthToken: "",
    pollingIntervalSeconds: 20,
    downloadDirectory: "~/Downloads/px-orders",
    hotFolderPath: "~/HotFolders/px",
    photoPrintHotFolderPath: "//PICSERVER/C8Spool",
    photoGiftHotFolderPath: "~/HotFolders/Sublimation",
    largeFormatHotFolderPath: "~/HotFolders/Large Format",
    largeFormatPhotozoneInputFolderPath: "~/HotFolders/Photo Zone Large Format Hot Folder",
    largeFormatPostsnapInputFolderPath: "~/HotFolders/Postsnap Large Format Hot Folder",
    largeFormatOutputFolderPath: "~/HotFolders/Large Format/Output",
    largeFormatBatchingIntervalMinutes: 10,
    largeFormatRollWidthIn: 36,
    largeFormatGapMm: 8,
    largeFormatLeaderMm: 50,
    largeFormatTrailerMm: 50,
    largeFormatLeftMarginMm: 5,
    largeFormatMaxBatchLengthMm: 1750,
    largeFormatAutoSend: false,
    largeFormatDirectPrint: false,
    largeFormatPrinterName: "",
    largeFormatAutoApproveEnabled: true,
    largeFormatAutoApproveMaxWastePercent: 20,
    largeFormatAutoBorderIfLightEdge: true,
    largeFormatEdgeBorderMm: 1,
    largeFormatPrintFilenameCaptions: true,
    largeFormatFilenameCaptionHeightMm: 6,
    largeFormatFilenameCaptionFontSizePt: 9,
    packingSlipPrinterName: "",
    shippingLabelPrinterName: "",
    useMockBackend: false,
  },
  scanner: {
    status: "disabled",
    port: null,
    lastScanAt: null,
    lastCode: null,
    recentScans: [],
  },
  jobs: [],
  logs: [],
  largeFormat: {
    jobs: [],
    batches: [],
    activity: [],
    activeBatchId: null,
    lastScanAt: null,
    lastProcessedAt: null,
  },
};
